config:
  deploy_template: '.sqa/docker-compose-plain.yml'
  #project_repos:
  #  onedatasim:
  #    repo: 'https://github.com/EOSC-synergy/onedataSim'
      #branch: main
      #branch: 'dev'
      #branch: ${GIT_LOCAL_BRANCH##*/} # I'd like to be a variable i.e GIT_BRANCH
      #branch: ${GIT_LOCAL_BRANCH}
      #branch: ${GIT_BRANCH##origin/}
      #branch: ${GIT_BRANCH}
sqa_criteria:
  #qc_style:
  QC.Sty
    repos:
      onedatasim:
        container: onedatasim-testing
        commands:
          # "Flake 8 is the wrapper which verifies pep8, pyflakes and circular complexity"
          # "The error code of flake8 are E***, W*** used in pep8 and F*** and C9**"   
          #  Alternative: hacking is a flake8' plug-in, based on OpenStack Style Guidlines, 
          #               which are based on Google Python Style Guide.
          - flake8 --max-line-length=162 /onedatasim-repo
  #qc_security:
  QC.Sec
    repos:
      onedatasim:
        # preliminary check of security, only plain code without execution
        container: onedatasim-testing
        commands: 
          - bandit -r /onedatasim-repo -x tests -s B110,B404,B602,B603
#  qc_doc:
#    repos:
#      onedatasim:
#        container: onedatasim-testing
#        commands:
#          - python setup.py build_sphinx
timeout: 900
