config:
  deploy_template: '.sqa/docker-compose-plain.yml'
  project_repos:
    onedatasim:
      repo: 'https://github.com/EOSC-synergy/onedataSim'
      branch: 'dev'
      #branch: ${GIT_LOCAL_BRANCH##*/} # I'd like to be a variable i.e GIT_BRANCH
      #branch: ${GIT_LOCAL_BRANCH}
      #branch: ${GIT_BRANCH##origin/}
sqa_criteria:
  qc_style:
    repos:
      onedatasim:
        container: onedatasim-testing
        commands:
          # "Flake 8 is the wrapper which verifies pep8, pyflakes and circular complexity"
          # "The error code of flake8 are E***, W*** used in pep8 and F*** and C9**"   
          #  Alternative: hacking is a flake8' plug-in, based on OpenStack Style Guidlines, 
          #               which are based on Google Python Style Guide.
          #- flake8 /onedatasim-repo
          - ls
  qc_security:
    repos:
      onedatasim:
        # preliminary check of security, only plain code without execution
        container: onedatasim-testing
        commands: 
          #- bandit -r /onedatasim-repo
          - ls
#  qc_doc:
#    repos:
#      onedatasim:
#        container: onedatasim-testing
#        commands:
#          - python setup.py build_sphinx
timeout: 900
