config:
  project_repos:
    onedatasim:
      repo: 'https://github.com/EOSC-synergy/onedataSim'
      branch: ${GIT_LOCAL_BRANCH##*/} # I'd like to be a variable i.e GIT_BRANCH
sqa_criteria:
  qc_style:
    repos:
      onedatasim:
        container: onedatasim-testing
        commands:
          # "Flake 8 is the wrapper which verifies pep8, pyflakes and circular complexity"
          # "The error code of flake8 are E***, W*** used in pep8 and F*** and C9**"   
          #  Alternative: hacking is a flake8' plug-in, based on OpenStack OpenStack Style Guidlines, 
          #               which are based on Google Python Style Guide.
          - flake8 /onedatasim-repo
  qc_security:
    repos:
      onedatasim:
        # preliminary check of security, only plain code without execution
        container: onedatasim-testing
        commands: 
          - bandit -r /onedatasim-repo
#  qc_doc:
#    repos:
#      onedatasim:
#        container: onedatasim-testing
#        commands:
#          - python setup.py build_sphinx
timeout: 900
