version: "3.6"
services:
  onedatasim-testing:
    image: "indigodatacloud/ci-images:python3.6"
    container_name: "onedatasim-testing"
    volumes:
     - type: bind
       source: ./onedatasim
       target: /onedatasim-repo
    #command: sleep 3600
  onedatasim-s0:
    container_name: "onedatasim-s0"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        # docker-hub releases will not need tokens to build never more
        # ONECLIENT_ACCESS_TOKEN_TO_BUILD: ${TOKEN_BUILD}
        # ONECLIENT_PROVIDER_HOST_TO_BUILD: "https://mon01-tic.ciemat.es"
        # but need a docker image, passed through argument (not by image param)
        BASE_OS : "lagocollaboration/lago-corsika:77402-dev"
        ONEDATASIM_BRANCH : "dev"
        ARTI_BRANCH : "dev"
    command: sleep 900
  onedatasim-s1:
    container_name: "onedatasim-s1"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        # but need a docker image, passed through argument (not by image param)
        BASE_OS : "centos:7"
        ONEDATASIM_BRANCH : "dev"
        ARTI_BRANCH : "dev"
    command: sleep 900
#  onedatasim-s2:
#    container_name: "onedatasim-s2"
#    build:
#      context: "."
#      dockerfile: "./Dockerfile"
#      args:
#        # but need a docker image, passed through argument (not by image param)
#        BASE_OS : "lagocollaboration/lago-geant:TAG"
#    command: sleep 900
