version: "3.7"
services:
  onedatasim-s1:
    container_name: "onedatasim-s1"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        # but need a docker image, passed through argument (not by image param)
        BASE_OS : "centos:7"
        ONEDATASIM_BRANCH : "dev"
        ARTI_BRANCH : "dev"
    # image, post-build is where it is stored
    image: "lagocollaboration/onedatasim-s1:latest"
    command: sleep 900
    # ..., doesn't work for fuse
    # volumes:
    # - source: /dev/fuse
    #  target: /dev/fuse
    #  type: bind
    # again, with fuse
    privileged: true
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    #  - DAC_READ_SEARCH
#  FAIR DISABLED FOR S1 (not planified in EOSC-synergy)
#  fair_eva:
#    #image: ferag/fair_eva:latest
#    #image: ferag/fair_eva:fair
#    image: lagocollaboration/fair_eva:9f4440903e14
#    command: bash -lc 'cd /FAIR_eva; /FAIR_eva/start.sh'
#    volumes:
#    - source: ./
#      target: /sqaaas-build
#      type: bind
#    working_dir: /sqaaas-build
#    #command: /FAIR_eva/start.sh
#    #command: apt-get install -y curl && /FAIR_eva/fair.py && /FAIR_eva/web.py
#    #command: apt-get install -y curl && /FAIR_eva/fair.py && /FAIR_eva/web.py && sleep 900
#  fair_uji:
#    #image: steinsteiny/fuji:fair
#    #image: steinsteiny/fuji:v1.4.9-noauth
#    image: lagocollaboration/fuji:v1.4.9-noauth
#    volumes:
#    - source: ./
#      target: /sqaaas-build
#      type: bind
#    working_dir: /sqaaas-build
