version: "3.7"
services:
  onedatasim-s1:
    container_name: "onedatasim-s1"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        # but need a docker image, passed through argument (not by image param)
        BASE_OS : "centos:7"
        ONEDATASIM_BRANCH : "dev"
        ARTI_BRANCH : "dev"
    # image, post-build is where it is stored
    image: "lagocollaboration/onedatasim-s1:latest"
    #command: sleep 900
  fair_eva:
    image: ferag/fair_eva:latest
    #image: ferag/fair_eva:fair
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
    #command: /FAIR_eva/start.sh
    #command: apt-get install -y curl && /FAIR_eva/fair.py && /FAIR_eva/web.py
  fair_uji:
    image: steinsteiny/fuji:fair
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
