version: "3.7"
services: 
  onedatasim-s0:
    container_name: "onedatasim-s0"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        # docker-hub releases will not need tokens to build never more
        # ONECLIENT_ACCESS_TOKEN_TO_BUILD: ${TOKEN_BUILD}
        # ONECLIENT_PROVIDER_HOST_TO_BUILD: "https://mon01-tic.ciemat.es"
        # but need a docker image, passed through argument (not by image param)
        BASE_OS : "lagocollaboration/lago-corsika:77402"
        ONEDATASIM_BRANCH : "dev"
        ARTI_BRANCH : "dev"
    # image, post-build is where it is stored
    image: "lagocollaboration/onedatasim-s0:dev"
    command: sleep 900
